package.json, src/ai-agents/createAssistant.ts, src/ai-agents/createRun.ts, src/ai-agents/handleRunToolCalls.ts, src/ai-agents/performRun.ts, src/constants/promts.ts, src/index.ts, yarn.lock
Closes: #XXXX
---
I have...
I have...
=> improve ai agent and clean dependencies

package.json, src/ai-agents/createAssistant.ts, src/ai-agents/performRun.ts, yarn.lock
Closes: #XXXX
---
I have...
I have...
=> add temperature config and logtime

CONTRIBUTING.md, package-lock.json, src/README.md, test/README.md, yarn.lock
Closes: #3 
---
I have...
I have...
=> add structure document

package.json, test/unit/getBalance.spec.ts, yarn.lock
Closes: #XXXX
---
I have...
I have...
=> add package for testing

src/constants/bendABI.ts, src/constants/index.ts, src/tools/allTools.ts, src/tools/bend/bendSupply.ts, src/tools/royco/bendSupply.ts, test/unit/bendSupply.spec.ts
Closes: #31
This PR introduces the initial structure and implementation of the adding liquidity lending functionality for the Bend protocol, along with comprehensive test coverage.
Key changes:
- Initialize core structure and basic adding liquidity for Bend protocol
- Implement unit tests covering:
+ Supply flows
=> feat(bend): implement liquidity lending functionality with tests

src/constants/promts.ts, src/tools/allTools.ts, src/tools/bgtStation/bgtStationDelegateBGT.ts, src/tools/bgtStation/bgtStationRedeem.ts
Closes: #23 
---
I have...
I have...
=> feat: redeem bgt

src/constants/yeetABI.ts
Adding the ABIs for the yeet ecosystem
=> feat: Add yeet ABIs

src/constants/promts.ts, src/tools/tavilySearch/liveSearch.ts
Closes: #XXXX
---
I have...
I have...
=> improve: add persona prompt

.github/workflows/release.yml, package.json, scripts/generate-dist-package.js
Deploy code into `gh-pages` branch. 
The project still alpha, so don't publish to npm right now
=> chore: update script deploy release package

.github/workflows/release.yml
Closes: #XXXX
---
I have...
I have...
=> chore: update semantic token

.github/workflows/release.yml, .releaserc.json
Closes: #XXXX
---
I have...
I have...
=> fix: resolve asset upload conflict by removing existing assets

src/tools/common/getBalance.ts, src/tools/tavilySearch/liveSearch.ts
Closes: #XXXX
---
I have...
I have...
=> fix: remove log noneeded

.releaserc.json
Closes: #XXXX
---
I have...
I have...
=> fix: update semantic release github

guides/usage-guide.md, test/unit/bendSupply.spec.ts
Closes: #XXXX
---
I have...
I have...
=> fix: remove log

.github/workflows/manual_release.yml
Closes: #XXXX
---
I have...
I have...
=> add manual release pipeline

src/tools/oogaBooga/oogaBoogaSwap.ts, src/utils/helpers.ts
Closes: #XXXX
---
I have...
I have...
=> fix: oogabooga swap

examples/basic-usage.ts, src/ai-agents/performRun.ts, src/constants/promts.ts
Closes: #XXXX
---
I have...
I have...
=> improve the agent to be able perform multiple actions

src/ai-agents/createAssistant.ts, src/ai-agents/handleRunToolCalls.ts, src/constants/promts.ts, src/index.ts
Closes: #XXXX
---
I have...
I have...
=> modify prompts

examples/basic-usage.ts, src/constants/chain.ts, src/utils/helpers.ts
Closes: #XXXX
---
I have...
I have...
=> fix: approve token error by ts check with add chain property

examples/basic-usage.ts, src/tools/kodiak/kodiakSwap.ts
- Updated kodiakSwap tool to support more flexible token swapping
- Added support for swapping to native token (BERA) via multicall
- Improved type checking and required parameters for swap operations
- Added logging for token input and output addresses
Closes: #XXXX
---
I have...
I have...
=> feat: enhance Kodiak swap functionality for native and token swaps

src/ai-agents/handleRunToolCalls.ts, src/ai-agents/performRun.ts, src/index.ts, src/tools/allTools.ts, src/tools/bex/bexSwap.ts, src/utils/createViemPublicClient.ts, src/utils/helpers.ts
Closes: #XXXX
---
I have...
I have...
=> refactor: update public client not optional

examples/basic-usage.ts, src/index.ts, src/tools/tavilySearch/liveSearch.ts
Closes: #XXXX
---
I have...
I have...
=> refine live search func

src/ai-agents/handleRunToolCalls.ts, src/ai-agents/performRun.ts, src/constants/types.ts, src/index.ts, src/tools/allTools.ts, src/tools/oogaBooga/oogaBoogaSwap.ts, src/tools/tavilySearch/liveSearch.ts
Closes: #XXXX
---
I have...
I have...
=> refactor: update agent config env
